### ISSUE TITLE
Failure to display a "null" result

### ISSUE THREAD

**Issue by lbguilherme** [sdkgen/playground#2]
When a function has return type "void" or optional it will/might return `null`. If this happens this error is shown to the user, even though the request was successful:

![image](https://user-images.githubusercontent.com/546954/71373814-33594800-2597-11ea-8656-60dcf57012bb.png)

**Comment by lbguilherme** [comment]
cc @kevinoliveira

**Comment by kevinoliveira** [comment]
please check the PR
